### ISSUE TITLE
Please 1. remove boost dependency 2. remove c++11 dependency

### ISSUE THREAD

**Issue by hughperkins** [rpavlik/luabind#28]
Hi,

I'd like to have the ability to do the following, ideally:
1. call c++ from lua.  This seems not so hard, eg this library probably does that. So does swig
2. override c++ classes from lua, and have c++ call back into those.  Swig doesnt do this.  I heard that luabind does?
3. not have to install boost.  it's easy to install on linux, not so easy on windows
4. be able to build using only c++0x and visual studio 2010.  visual studio 2010 is the current version used by python, that I'm also linking with.  c++0x is still the highest standard in many commonly available gcc versions

**Comment by rpavlik** [comment]
1 and 2 are both in the docs.

3: Sorry, not likely to be able to remove boost dependency from this lib, though you might be interested in the boost Windows binaries here: http://sourceforge.net/projects/boost/files/boost-binaries/  If you can't use boost, I'd suggest using one of the other Lua binding libraries like this - I know there are some with a similar style that don't use boost.

4: well, C++0x is the "pre-release" name for the standard that became C++11, so that's actually the same. That said, VS2010 supports just a small amount of this modern C++ standard, so that is a distinct benchmark to go by. Last time I tried this worked with VS2008, even - if some C++11 snuck in when I wasn't looking I'd appreciate specific reports (and ideally patches) on it.
